In [1]:
import pandas as pd

file_path = "../data/raw/airfoil_self_noise.dat"

df = pd.read_csv(
    file_path,
    sep="\t",
    header=None
)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (1503, 6)

      0    1       2     3         4        5
0   800  0.0  0.3048  71.3  0.002663  126.201
1  1000  0.0  0.3048  71.3  0.002663  125.201
2  1250  0.0  0.3048  71.3  0.002663  125.951
3  1600  0.0  0.3048  71.3  0.002663  127.591
4  2000  0.0  0.3048  71.3  0.002663  127.461

In [2]:
print("Data types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Data types:
0      int64
1    float64
2    float64
3    float64
4    float64
5    float64
dtype: object

Missing values:
0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

Duplicate rows: 0

In [3]:
print(df.describe())

                  0            1            2            3            4  \
count   1503.000000  1503.000000  1503.000000  1503.000000  1503.000000
mean    2886.380572     6.782302     0.136548    50.860745     0.011140
std     3152.573137     5.918128     0.093541    15.572784     0.013150
min      200.000000     0.000000     0.025400    31.700000     0.000401
25%      800.000000     2.000000     0.050800    39.600000     0.002535
50%     1600.000000     5.400000     0.101600    39.600000     0.004957
75%     4000.000000     9.900000     0.228600    71.300000     0.015576
max    20000.000000    22.200000     0.304800    71.300000     0.058411

                 5
count  1503.000000
mean    124.835943
std       6.898657
min     103.380000
25%     120.191000
50%     125.721000
75%     129.995500
max     140.987000

In [4]:
df.columns = [
    "frequency_hz",
    "angle_of_attack_deg",
    "chord_length_m",
    "free_stream_velocity_ms",
    "suction_side_displacement_thickness_m",
    "scaled_sound_pressure_db"
]

df.head()

,frequency_hz,angle_of_attack_deg,chord_length_m,free_stream_velocity_ms,suction_side_displacement_thickness_m,scaled_sound_pressure_db
0,800,0.0,0.3048,71.3,0.002663,126.201
1,1000,0.0,0.3048,71.3,0.002663,125.201
2,1250,0.0,0.3048,71.3,0.002663,125.951
3,1600,0.0,0.3048,71.3,0.002663,127.591
4,2000,0.0,0.3048,71.3,0.002663,127.461

In [5]:
print(df.info())
print("\nColumn names:")
print(df.columns.tolist())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 6 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   frequency_hz                           1503 non-null   int64
 1   angle_of_attack_deg                    1503 non-null   float64
 2   chord_length_m                         1503 non-null   float64
 3   free_stream_velocity_ms                1503 non-null   float64
 4   suction_side_displacement_thickness_m  1503 non-null   float64
 5   scaled_sound_pressure_db               1503 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 70.6 KB
None

Column names:
['frequency_hz', 'angle_of_attack_deg', 'chord_length_m', 'free_stream_velocity_ms', 'suction_side_displacement_thickness_m', 'scaled_sound_pressure_db']